baseurl = "https://ocean.github.io/explicator/"
languageCode = "en-au"
title = "Explicator"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ocean/explicator"
[[menu.main]]
    name = "Twitter"
    url = ""

[params]
    description = "Robot git helper."

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50